---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Reload ansible_facts
  setup:

- name: Copy the EPEL repository definition
  template: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  template: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: Set up iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables
